# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99f1896b01b96efce3602c6669618729361172cb7ed54729b972e08480556154fe466022502996122b48254589b8d43cad29b52a7276fa89f4e4d4610e4e5f35

test:
  secret_key_base: 779dc47982afa3caff47f639f8ed109f7dde501f6c89a11aa12c5ef4f3ddb4f5597b9fa8c2119aef28ae64daa9cb53f4694c1f4b3c2c8a5b86a592ceb9efb4ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
