# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6e87460230ee1679c3f4c2459c95e483729dfc3c95510c4ad737b4d5cad6021ffaef9103f8e738b432b2ce8860970428997ac5b3b8fdeed7acfb9b209ce867c

test:
  secret_key_base: 88de577a599edfa38fb6f0cfe7c19004ca9c0eaf0e675699df3918216094d8053eda49a45d8b8bd7245a312ddd8d47067bd85b9444bfa9f65221bf9d677ed5e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
