# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8c0adf2b8bb8b45f76a7d5dfb2ddc977562b6fef862d572e74df9051e94021e8fbe65d06c4f0fb87db640c06f8d03cc5de73c72991856545e5bd819e476114f

test:
  secret_key_base: f1ae953677921f000d37070d73520b3f718bc18cbd4ea4d3a56f685ded4364edbd0cbbffbe0c14323674593a504b2bf90ef8493802f20f7c37e1cb74d1cc42e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
